baseurl = "https://apiotrowski.xyz"
title = "Aleksander Piotrowski"
theme = "tale"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[Author]
    name = "Aleksander Piotrowski"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    title = "Tags"
#    url = "/tags/"
#    weight = 0

