site_name: apiotrowski.xyz
site_url: https://apiotrowski.xyz

theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
  palette: {}
  custom_dir: overrides
  
extra_css:
  - assets/extra.css

plugins:
  - search
  - blog:
      blog_dir: .

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/piotrowski
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/aleksander-piotrowski-266a8519b/
  analytics:
    provider: custom
    property: https://apiotrowski312.goatcounter.com/count
  consent:
    title: Tracking consent
    description: >- 
      I use GoatCounter.com to count unique visitors. Following information might be stored:
      URL of the visited page. 
      Referer header. 
      Browser and system information (derived from User-Agent header or HTTP client hints; the original headers are not stored). 
      Screen size. Country and region name derived from the IP address. 
      The browser language derived from the Accept-Language header. 
    analytics:
      name: GoatCounter.com
      checked: true
    actions:
      - accept
      - reject

copyright: >
  Copyright &copy; 2024 Aleksander Piotrowski –
  <a href="#__consent">Change tracking settings</a>

nav:
  - Home:
    - index.md
  - About: about.md